### ISSUE TITLE
Add FindBugs as pre-commit hook in Idea

### ISSUE THREAD

**Issue by cezary-butler** [andrepdo/findbugs-idea#116]
It would be great if FindBugs plugin could be added as a pre commit hook similarly as idea inspections.
For that there is a checkbox in the commit dialog, after some inspections fail, message box with summary appears and user can opt in to view results or commit instead.

**Comment by retomerz** [comment]
Implemented in v0.9.999. Please update the plugin.

Note that in this case the FindBugs-IDEA setting "Compile before analyze" (introduced with v0.9.998)
is ignored because the IDEA CheckinHandler API is synchronous and the Compiler API asynchronous.

Thank you for taking the time to submit the issue!
